# -*- coding: utf-8 -*-
"""Single-variable bisection, starting from the state that ALREADY WORKS.

`test_plumbing` passed: 11 original blocks copied, appended, table rebuilt.
From there ONE thing changes at a time:

  (no flag)    identical to plumbing (control: it has to pass)
  --reencode   the same 11 blocks, but generated by make_block
  --split N    split the largest block into N pieces -> 11+N-1 blocks

    python test_minimal.py --reencode
    python test_minimal.py --split 2
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import struct
import importlib.util as _iu
_SP = _iu.spec_from_file_location(
    'mc3_output', os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              '..', 'mc3_output.py'))
_out_path = _iu.module_from_spec(_SP)
_SP.loader.exec_module(_out_path)


HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('conv', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'mc2_to_mc3.py'))
conv = importlib.util.module_from_spec(spec)
spec.loader.exec_module(conv)

SRC = os.path.join(os.environ.get('MC3_ASSETS', 'ASSETS'), 'resources/city/atlanta_midnight_clear.pck')
TARGET = 'a_inst_low_ghto_06x'      # no block has per-vertex colour




def append_array(d, body, n, align=16):
    """Append an array WITH THE 16-BYTE HEADER the game expects.

    Found in the mesh constructor (`sub_2A8FA0` in the ELF): it allocates
    `n*8 + 16`, writes the COUNT at the start of the buffer and keeps the
    pointer aimed 16 BYTES PAST it. So `[ptr - 16]` is the element count.
    Checked on retail: 6/6 groups and 6/6 block lists of the target. I never
    wrote it -- 0xCDCDCDCD sat there.
    """
    pad = 0xCD
    while len(d) % align:
        d.append(pad)
    d.extend(struct.pack("<I", n))
    d.extend(bytes([pad]) * 12)
    body_at = len(d)
    d.extend(body)
    while len(d) % align:
        d.append(pad)
    struct.pack_into("<I", d, 0x0C, len(d) - 0x80)
    return body_at



def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--reencode', action='store_true')
    ap.add_argument('--split', type=int, default=0)
    ap.add_argument('--spread', action='store_true',
                    help='split one block in 3 DIFFERENT groups: same total, same maximum per group')
    ap.add_argument('--out-path', default=None)
    a = ap.parse_args()

    d = bytearray(open(SRC, 'rb').read())
    va = struct.unpack_from('<I', d, 0)[0]
    base = va - 0x80
    F = lambda v: v - base
    V = lambda o: o + base
    U = lambda o: struct.unpack_from('<I', d, o)[0]

    for o in range(0x80, len(d) - 0x80, 4):
        if U(o) == 0x7A0090 and bytes(d[o + 0x48:o + 0x70]).split(b'\0')[0] == TARGET.encode():
            vt = o
            break
    mesh = F(U(vt + 0x14))
    ngrp = struct.unpack_from('<H', d, mesh + 8)[0]
    g = F(U(mesh + 0x10))

    groups = []
    for k in range(ngrp):
        p, c, _ = struct.unpack_from('<IHH', d, g + 8 * k)
        lf = F(p)
        entries_ = []
        for j in range(c):
            bp, qw, nv = struct.unpack_from('<IHH', d, lf + 8 * j)
            blk = F(bp)
            sc = struct.unpack_from('<f', d, blk + 4)[0]
            pos = [tuple(x * sc for x in struct.unpack_from('<hhh', d, blk + 0x10 + 6 * i))
                   for i in range(nv)]
            u0 = blk + 0x10 + 6 * nv
            while u0 % 4:
                u0 += 1
            uv = [tuple(x / 4096.0 for x in struct.unpack_from('<hh', d, u0 + 4 + 4 * i))
                  for i in range(nv)]
            odd = bytes(d[blk + 0x0C:blk + 0x0E]) == b'\x27\x02'
            entries_.append(dict(bytes=bytes(d[blk:blk + qw * 16]), qw=qw, nv=nv,
                              pos=pos, uv=uv, odd=odd, sc=sc))
        groups.append(entries_)

    # --split: split the largest block into N strips (overlapping by 2, keeps the strip)
    if a.split > 1:
        largest = max((it for gr in groups for it in gr), key=lambda x: x['nv'])
        gi = next(i for i, gr in enumerate(groups) if largest in gr)
        gr = groups[gi]
        idx = gr.index(largest)
        n = largest['nv']
        step = max(3, (n + a.split - 1) // a.split)
        chunks = []
        s = 0
        while s < n - 2:
            p2, u2 = largest['pos'][s:s + step + 2], largest['uv'][s:s + step + 2]
            if len(p2) >= 3:
                chunks.append(dict(pos=p2, uv=u2, odd=largest['odd'], sc=largest['sc'],
                                    nv=len(p2), bytes=None, qw=None))
            s += step
        gr[idx:idx + 1] = chunks
        print('block of %d vertices (group %d) split into %d pieces of up to %d'
              % (n, gi, len(chunks), step + 2))

    # --spread: reach the same block total WITHOUT raising the per-group maximum.
    # Separates "more blocks in the mesh" from "more blocks in one group".
    if a.spread:
        targets = [i for i, gr in enumerate(groups) if len(gr) == 1][:3]
        for gi in targets:
            it = groups[gi][0]
            n = it['nv']
            if n < 8:
                continue
            middle = (n // 2) + (n // 2) % 2          # an EVEN cut point keeps the parity
            a1 = dict(it, pos=it['pos'][:middle + 2], uv=it['uv'][:middle + 2],
                      nv=middle + 2, bytes=None, qw=None)
            a2 = dict(it, pos=it['pos'][middle:], uv=it['uv'][middle:],
                      nv=n - middle, bytes=None, qw=None)
            groups[gi] = [a1, a2]
        print('groups %s split in 2 -> counts %s'
              % (targets, [len(g) for g in groups]))

    def append(blob, align=16):
        while len(d) % align:
            d.extend(b'\xCD')
        at = len(d)
        d.extend(blob)
        while len(d) % align:
            d.extend(b'\xCD')
        struct.pack_into('<I', d, 0x0C, len(d) - 0x80)
        return at

    tab = bytearray()
    nb = 0
    for gr in groups:
        lb = bytearray()
        for it in gr:
            if it['bytes'] is not None and not a.reencode:
                blob, qw, nv = it['bytes'], it['qw'], it['nv']
            else:
                blob = conv.make_block(it['pos'], it['uv'], it['sc'], it['odd'])
                qw, nv = len(blob) // 16, len(it['pos'])
            tab_at = append(blob)
            lb += struct.pack('<IHH', V(tab_at), qw, nv)
            nb += 1
        tab += struct.pack('<IHH', V(append_array(d, bytes(lb), len(gr))), len(gr), 0xCDCD)
    struct.pack_into('<I', d, mesh + 0x10,
                     V(append_array(d, bytes(tab), len(groups))))

    suffix = ('_reencoded' if a.reencode else '') + ('_split%d' % a.split if a.split > 1 else '')
    out = a.out_path or _out_path.path( 'test_minimal%s_atlanta_midnight_clear.pck' % suffix)
    open(out, 'wb').write(bytes(d))
    orig = open(SRC, 'rb').read()
    print('%d blocks in %d groups | %s' % (nb, len(groups), os.path.basename(out)))
    print('   %d bytes changed in the original region'
          % sum(1 for x, y in zip(orig, d) if x != y))


if __name__ == '__main__':
    main()
