"""Append the mip fallback installation to the shared fork log."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', 'tools'))


def main() -> int:
    changed = (
        "NATIVE MIP FALLBACK GENERATED, AUDITED AND INSTALLED in the nine base Mod City PCKs and in "
        "losangeles_midnight_clear.ppf. The C++ Fork log confirmed that draw_distance only writes the "
        "K/L bias the GS uses at build time; it does not create levels. The direct inventory showed "
        "that LA had 56 mip1 textures, 453 mip2 and 1 mip3, while the retail cities mostly use "
        "mip3. The 56 mip1 and the existing mip3 were kept intact; each of the 453 mip2 got a "
        "third 1/4 level generated by an indexed box filter and remapped to the original palette. "
        "Pixels and CLUT were encoded by native_texture_codec, derived from the ELF, not by the "
        "generic swizzle. For each expansion the GS descriptor, allocation fields and TEX1 were "
        "copied from a retail rmcTexturePS2 with the same width, height, PSM and 3 mips; the "
        "datChunkRefs were repointed by the identity of the old chunk. Active result: 56 mip1 + "
        "454 mip3, 1418 chunks, 53 pages, 498/510 chains whole in one page, PPF SHA-256 "
        "4399A30DF3B62609B91350898FEFFAEC2029659027589D8991E7FD315EA67D10 and midnight_clear.pck "
        "SHA-256 30D98F5B627AEE7B3741B22CA5612ED78A6954BC9766D7547AFA2C5F624DEF5C."
    )
    affects = (
        "Any fork that replaces losangeles_midnight_clear.ppf or the nine losangeles_{dawn,dusk,midnight}_"
        "{clear,cloudy,rainy}.pck; LOD/streaming diagnostics and the C++ Fork draw_distance. No .mod, "
        "geometry, PVS, graph or sky was changed."
    )
    action = (
        "TEST ONLY WITH A CLEAN BOOT: an old savestate keeps the earlier TexturePS2 and pages in "
        "RAM. In CTT10, confirm PPF123 with 53 pages and watch LOD 0/1/2; not every page is "
        "expected to be resident at the same time. Post-install audit: zero codec/palette/descriptor "
        "mismatch, zero multi-owner, zero unexpected bytes in the nine PCKs and 10/10 valid sky slots "
        "in each. Recoverable backup in backups/Fork City TEXTURES/2026-09-13_mip_fallback_v4; "
        "artefacts and audits in the after subdirectory."
    )
    result = subprocess.run(
        [sys.executable, str(ROOT / "mc3_forks.py"), "add",
         "--fork", "Fork City TEXTURES", "--changed", changed,
         "--affects", affects, "--action", action],
        cwd=ROOT,
        check=False,
    )
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
