"""Interactive terminal menu for MUX/DEMUX of Sony .bnk (989SND/SCREAM) files."""
import os
import sys
import json

from .parser import parse_bnk, BnkParseError
from .demux import demux
from .mux import mux, BnkMuxError
from .model import FULL_SUPPORT_VERSIONS, DEMUX_ONLY_VERSIONS, EXPERIMENTAL_MUX_VERSIONS
from .builder import build_bnk_v3, SoundSpec, grain_from_genh, BuildError, sounds_from_genh_folder


def _ask(prompt, default=None):
    suffix = f" [{default}]" if default is not None else ""
    while True:
        val = input(f"{prompt}{suffix}: ").strip().strip('"')
        if not val and default is not None:
            return default
        if val:
            return val
        print("  (required)")


def _ask_path(prompt, default=None, must_exist=True):
    while True:
        val = _ask(prompt, default)
        if not must_exist or os.path.exists(val):
            return val
        print(f"  file/folder not found: {val}")


def _ask_yesno(prompt, default=True):
    d = "Y/n" if default else "y/N"
    while True:
        val = input(f"{prompt} ({d}): ").strip().lower()
        if not val:
            return default
        if val in ("y", "yes"):
            return True
        if val in ("n", "no"):
            return False


def _print_support_note(sblk_version, support_tier):
    if support_tier == "full":
        return
    if support_tier == "demux_only":
        print(f"  warning: SBlk version 0x{sblk_version:02x} only supports reading/extraction (DEMUX). "
              f"Rebuilding (MUX) this stream is not safely possible (there is no size field).")
    elif support_tier == "experimental":
        print(f"  warning: SBlk version 0x{sblk_version:02x} has experimental support (not tested against "
              f"real files). Check the result carefully before using it in the game.")
    else:
        print(f"  warning: SBlk version 0x{sblk_version:02x} is not recognised by this table support; "
              f"extraction may fail.")


def cmd_info(path=None):
    path = path or _ask_path("Path of the .bnk file")
    try:
        h = parse_bnk(path)
    except BnkParseError as e:
        print(f"Error parsing the file: {e}")
        return
    print()
    for line in h.summary_lines():
        print(line)
    _print_support_note(h.sblk_version, h.support_tier)
    print()
    print(f"{'#':>4} {'name':<24} {'codec':<8} {'ch':>2} {'sample_rate':>11} {'loop':<6} {'size':>10}")
    for s in h.streams:
        loop = f"{s.loop_start}-{s.loop_end}" if s.loop_flag else "no"
        print(f"{s.index:>4} {s.name[:24]:<24} {s.codec:<8} {s.channels:>2} {s.sample_rate:>11} "
              f"{loop:<6} {s.stream_size:>10}")
        for w in s.warnings:
            print(f"       ! {w}")
    return h


def cmd_demux():
    path = _ask_path("Path of the .bnk file to extract")
    default_out = os.path.splitext(path)[0] + "_extracted"
    out_dir = _ask("Output folder", default_out)
    use_genh = _ask_yesno(
        "Extract as .genh (with header, editable/playable in any player with vgmstream)?", default=True)
    td_path = None
    default_td = os.path.splitext(path)[0] + ".td"
    if os.path.exists(default_td):
        if _ask_yesno(f"Found {os.path.basename(default_td)} - use it to name the streams?", default=True):
            td_path = default_td
    elif _ask_yesno("Do you have a .td file to name the streams?", default=False):
        td_path = _ask_path("Path of the .td")
    try:
        manifest_path = demux(path, out_dir, use_genh=use_genh, td_path=td_path)
    except BnkParseError as e:
        print(f"Error parsing the file: {e}")
        return
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)
    print()
    print(f"OK: {len(manifest['streams'])} streams extracted to: {out_dir}")
    print(f"Manifest: {manifest_path}")
    tier = manifest["support_tier"]
    if tier != "full":
        _print_support_note(manifest["sblk_version"], tier)
    n_genh = sum(1 for s in manifest["streams"] if s["container"] == "genh")
    n_raw = sum(1 for s in manifest["streams"] if s["container"] == "raw")
    if n_genh:
        print(f"{n_genh} stream(s) extracted as .genh")
    if n_raw:
        print(f"{n_raw} stream(s) extracted as raw (codec with no GENH equivalent)")
    any_warn = [s for s in manifest["streams"] if s["warnings"]]
    if any_warn:
        print(f"({len(any_warn)} streams with warnings - see manifest.json or run the Info option for details)")


def cmd_mux():
    print("MUX needs: the ORIGINAL .bnk (used as a template) + the folder generated by DEMUX (with "
          "manifest.json and the streams, original or replaced).")
    original = _ask_path("Path of the ORIGINAL .bnk file (template)")
    folder = _ask_path("Folder with manifest.json (generated by DEMUX)")
    manifest_path = folder if folder.lower().endswith(".json") else os.path.join(folder, "manifest.json")
    if not os.path.exists(manifest_path):
        print(f"manifest.json not found at: {manifest_path}")
        return

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    print(f"\n{len(manifest['streams'])} streams in this bank:")
    for s in manifest["streams"]:
        zlsd = " [ZLSD]" if s.get("is_zlsd") else ""
        print(f"  #{s['index']:<3} {s['name'][:24]:<24} {s['codec']:<8} current file: {s['file']}{zlsd}")

    overrides = {}
    print("\nType a stream number to replace its audio (or ENTER to finish the selection).")
    print("The replacement file must be in the SAME CODEC (already encoded correctly) - "
          "this tool does no re-encoding. It can be a .genh (the header is removed "
          "automatically and loop/channels edited in the .genh are applied when possible) or plain raw.")
    while True:
        idx_s = input("Stream # to replace (ENTER to stop): ").strip()
        if not idx_s:
            break
        if not idx_s.isdigit() or int(idx_s) not in [s["index"] for s in manifest["streams"]]:
            print("  invalid number")
            continue
        idx = int(idx_s)
        new_file = _ask_path(f"  new audio file for stream #{idx}")
        ov = {"file": new_file}
        if _ask_yesno("  also adjust the loop flag of this stream?", default=False):
            ov["loop_flag"] = _ask_yesno("  should the stream loop?", default=True)
        overrides[idx] = ov

    td_renames = {}
    if manifest.get("td") and _ask_yesno("\nRename any sound (affects only the .td, not the .bnk)?", default=False):
        by_index = {}
        for s in manifest["streams"]:
            if s.get("sound_index") is not None:
                by_index.setdefault(s["sound_index"], s["name"])
        for i in sorted(by_index):
            print(f"  sound #{i}: {by_index[i]}")
        while True:
            idx_s = input("Sound # to rename (ENTER to stop): ").strip()
            if not idx_s:
                break
            if not idx_s.isdigit() or int(idx_s) not in by_index:
                print("  invalid number")
                continue
            new_name = _ask(f"  new name for sound #{idx_s}")
            td_renames[int(idx_s)] = new_name

    default_out = os.path.splitext(original)[0] + "_new.bnk"
    out_path = _ask("Path of the output .bnk", default_out)
    if os.path.abspath(out_path) == os.path.abspath(original):
        print("For safety, the output file cannot be the same as the original.")
        return

    try:
        path, report = mux(original, manifest_path, out_path, overrides=overrides, td_renames=td_renames)
    except BnkMuxError as e:
        print(f"Error rebuilding the file: {e}")
        return

    print(f"\nOK: file rebuilt at: {path}")
    for line in report:
        print(f"  - {line}")


def _cmd_build_folder():
    folder = _ask_path("Folder with the .genh files")
    try:
        sounds = sounds_from_genh_folder(folder)
    except BuildError as e:
        print(f"Error: {e}")
        return None

    print(f"\n{len(sounds)} sound(s) detected from the file names:")
    for snd in sounds:
        grain_info = ", ".join(f"{g.sample_rate}Hz" for g in snd.grains)
        print(f"  {snd.name}  ({len(snd.grains)} grain(s): {grain_info})")

    if not _ask_yesno("\nUse these names/groupings?", default=True):
        return None
    return sounds


def _cmd_build_manual():
    sounds = []
    while True:
        name = input("\nSound name (ENTER to finish): ").strip()
        if not name:
            break
        grains = []
        while True:
            genh_path = input(
                f"  .genh file for '{name}' (ENTER to stop adding audio to this sound): "
            ).strip().strip('"')
            if not genh_path:
                break
            if not os.path.exists(genh_path):
                print("  file not found")
                continue
            try:
                g = grain_from_genh(genh_path)
            except BuildError as e:
                print(f"  error: {e}")
                continue
            if _ask_yesno(f"  current sample_rate: {g.sample_rate} Hz - change it?", default=False):
                g.sample_rate = int(_ask("  new sample_rate (Hz)"))
            grains.append(g)
        if not grains:
            print(f"  sound '{name}' has no audio, ignored")
            continue
        sounds.append(SoundSpec(name=name, grains=grains))
    return sounds


def cmd_build():
    print("BUILD creates a NEW .bnk from scratch, without needing an original file as a template.")
    print("Warning: some table fields (not read by vgmstream) were filled with values")
    print("observed in real banks - validated in vgmstream, but not in the game engine itself.")
    print("Test in the game before using it for real.")
    print("Each 'sound' (the name the game uses) can have 1+ audio variations (grains), each one a")
    print("mono .genh in PSX (PS-ADPCM) or PCM16.")

    print("\n1) Folder with several .genh at once (names the sounds after the file names)")
    print("2) Add one sound at a time, by hand")
    mode = input("> ").strip()

    if mode == "1":
        sounds = _cmd_build_folder()
        if sounds is None:
            return
    else:
        sounds = _cmd_build_manual()

    if not sounds:
        print("no sound defined, cancelled")
        return

    out_path = _ask("Path of the output .bnk", "new.bnk")
    try:
        bnk_bytes, manifest, td_text = build_bnk_v3(sounds)
    except BuildError as e:
        print(f"Error while building: {e}")
        return

    with open(out_path, "wb") as f:
        f.write(bnk_bytes)
    td_path = os.path.splitext(out_path)[0] + ".td"
    with open(td_path, "w", encoding="latin-1") as f:
        f.write(td_text)

    print(f"\nOK: {len(sounds)} sound(s) / {len(manifest['streams'])} stream(s)")
    print(f".bnk: {out_path}")
    print(f".td:  {td_path}")
    print("Reminder: test in the game before using it for real.")


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]

    if argv:
        return _main_args(argv)

    print("=" * 60)
    print(" BNK MUX/DEMUX - Sony 989SND/SCREAM (.bnk/.mus/.sbk)")
    print(" based on VGMStream's bnk_sony.c reader")
    print("=" * 60)
    while True:
        print("\n1) DEMUX  - extract streams from a .bnk")
        print("2) MUX    - rebuild a .bnk from streams (uses an original .bnk as a template)")
        print("3) BUILD  - create a new .bnk from scratch (no template)")
        print("4) Info   - show information/streams of a .bnk")
        print("5) Quit")
        choice = input("> ").strip()
        try:
            if choice == "1":
                cmd_demux()
            elif choice == "2":
                cmd_mux()
            elif choice == "3":
                cmd_build()
            elif choice == "4":
                cmd_info()
            elif choice == "5":
                break
            else:
                print("invalid option")
        except KeyboardInterrupt:
            print("\ncancelled")
        except Exception as e:
            print(f"Unexpected error: {e}")


def _main_args(argv):
    import argparse
    p = argparse.ArgumentParser(prog="bnkmux", description="MUX/DEMUX of Sony .bnk files (989SND/SCREAM)")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_demux = sub.add_parser("demux", help="extract streams from a .bnk")
    p_demux.add_argument("bnk")
    p_demux.add_argument("out_dir")
    p_demux.add_argument("--raw", action="store_true",
                          help="extract plain raw instead of .genh (no header)")
    p_demux.add_argument("--td", help=".td file to name the streams")

    p_mux = sub.add_parser("mux", help="rebuild a .bnk from a manifest (uses a template)")
    p_mux.add_argument("original_bnk")
    p_mux.add_argument("manifest")
    p_mux.add_argument("out_bnk")
    p_mux.add_argument("--replace", action="append", default=[],
                        help="INDEX=file, can be repeated to replace several streams")
    p_mux.add_argument("--rename", action="append", default=[],
                        help="SOUND_INDEX=new_name, renames a sound in the generated .td")

    p_build = sub.add_parser("build", help="create a new .bnk from scratch, without a template")
    p_build.add_argument("out_bnk")
    build_src = p_build.add_mutually_exclusive_group(required=True)
    build_src.add_argument("--dir", help="folder with several .genh; one sound per file name "
                            "(grouping 001_NAME.genh + 002_NAME.genh into the same sound)")
    build_src.add_argument("--spec", help='JSON: {"sounds":[{"name":.., '
                            '"grains":[{"file":"x.genh","sample_rate":40000}]}]}')

    p_info = sub.add_parser("info", help="show information about a .bnk")
    p_info.add_argument("bnk")

    args = p.parse_args(argv)

    if args.cmd == "demux":
        manifest_path = demux(args.bnk, args.out_dir, use_genh=not args.raw, td_path=args.td)
        print(f"OK: {manifest_path}")
    elif args.cmd == "info":
        cmd_info(args.bnk)
    elif args.cmd == "mux":
        overrides = {}
        for item in args.replace:
            idx_s, _, fpath = item.partition("=")
            overrides[int(idx_s)] = {"file": fpath}
        td_renames = {}
        for item in args.rename:
            idx_s, _, new_name = item.partition("=")
            td_renames[int(idx_s)] = new_name
        path, report = mux(args.original_bnk, args.manifest, args.out_bnk, overrides=overrides,
                            td_renames=td_renames)
        print(f"OK: {path}")
        for line in report:
            print(f"  - {line}")
    elif args.cmd == "build":
        if args.dir:
            sounds = sounds_from_genh_folder(args.dir)
        else:
            with open(args.spec, encoding="utf-8") as f:
                spec = json.load(f)
            sounds = []
            for snd in spec["sounds"]:
                grains = []
                for gspec in snd["grains"]:
                    g = grain_from_genh(gspec["file"])
                    if gspec.get("sample_rate"):
                        g.sample_rate = gspec["sample_rate"]
                    if "loop_flag" in gspec:
                        g.loop_flag = gspec["loop_flag"]
                    grains.append(g)
                sounds.append(SoundSpec(name=snd["name"], grains=grains,
                                         priority=snd.get("priority", 0x78), td_flag=snd.get("td_flag", 1)))
        bnk_bytes, manifest, td_text = build_bnk_v3(sounds)
        with open(args.out_bnk, "wb") as f:
            f.write(bnk_bytes)
        td_path = os.path.splitext(args.out_bnk)[0] + ".td"
        with open(td_path, "w", encoding="latin-1") as f:
            f.write(td_text)
        print(f"OK: {args.out_bnk}")
        print(f"OK: {td_path}")


if __name__ == "__main__":
    main()
