"""Inventory of the Midnight Club 2 city assets.

Written for one question: what would have to be converted to bring an MC2 city
into MC3, and how much of it is readable.

The answer is the reason this file exists. Almost the whole MC2 city is PLAIN
TEXT - meshes included. That is the opposite of the MC:LA PSP attempt, which was
binary on both ends and stalled on a vertex encoding neither side documented.
Here there is no encoding to reverse: the vertices are decimal numbers on lines
beginning with `v`.

    python mc2_inventory.py [MC2 folder] [-o report.md]

Re-run it as more is learned; the descriptions live in FORMATOS below and are
meant to be edited.
"""
import io
import os
import sys

DEFAULT_ROOT = os.path.dirname(os.environ.get('MC2_PC_ASSETS', 'mc2_pc/assets_p'))

# What each extension is, as far as it has been established. An entry with a
# question mark is a guess from one sample, not a finding.
FORMATS = {
    'lvl':     ('texto', 'the city: hood count, world extents, grid dimensions, hood names'),
    'hood':    ('texto', 'a neighbourhood: unique components (name + AABB) and their instances'),
    'xmod':    ('texto', 'the MESH. verts/normals/colors/tex1s/materials/primitives, then `v x y z` lines'),
    'cc':      ('texto', 'per-component: inst_cpv, bounding sphere, and which LODs exist'),
    'pdef':    ('texto', 'prop definition: name, LOD list, bounding sphere'),
    'mm':      ('texto', 'same shape as pdef, used for breakable pieces'),
    'gt':      ('texto', 'lighting: ambient colour and friends'),
    'inf':     ('texto', 'flat list, `group : index name` - component to something mapping'),
    'prop':    ('texto', 'placed props'),
    'sndref':  ('texto', 'named sound regions with bounds'),
    'algt':    ('texto', 'area light types'),
    'occlude': ('texto', 'occlusion volumes'),
    'txt':     ('texto', 'build logs left in the shipped data (exported / finished / xbox)'),
    'aib':     ('binario', 'AI paths. Header TSV1'),
    'pvc':     ('binario', 'per-vertex colours for the base condition'),
    'cpvs':    ('binario', 'per-vertex shading, one file per city x time x weather (27 total)'),
}

INTERESTING = ('lvl', 'hood', 'xmod', 'cc', 'pdef', 'mm', 'gt', 'inf', 'prop',
             'sndref', 'algt', 'occlude', 'txt', 'aib', 'pvc')


def is_text(path, sample=2048):
    try:
        d = open(path, 'rb').read(sample)
    except OSError:
        return None
    if not d:
        return None
    imp = sum(1 for b in d if 32 <= b < 127 or b in (9, 10, 13))
    return imp / len(d) > 0.92


def scan(root):
    """{extension: [paths]} of everything under `root`."""
    por_ext = {}
    for base, _dirs, files in os.walk(root):
        for f in files:
            e = os.path.splitext(f)[1].lower().lstrip('.')
            por_ext.setdefault(e, []).append(os.path.join(base, f))
    return por_ext


def size(paths):
    t = 0
    for p in paths:
        try:
            t += os.path.getsize(p)
        except OSError:
            pass
    return t


def head(path, lines=6):
    try:
        with io.open(path, encoding='latin1') as fh:
            return [next(fh).rstrip('\n') for _ in range(lines)]
    except (OSError, StopIteration):
        try:
            with io.open(path, encoding='latin1') as fh:
                return [l.rstrip('\n') for l in fh]
        except OSError:
            return []


def report(root, out_path):
    city = os.path.join(root, 'assets_p', 'city')
    if not os.path.isdir(city):
        raise SystemExit('not found: %s' % city)

    L = []
    W = L.append
    W('# MC2 city assets')
    W('')
    W('Generated by `mc2_inventory.py`. Source: `%s`' % root)
    W('')
    W('## The finding that matters')
    W('')
    W('**Almost the entire MC2 city is plain text, meshes included.** Only the AI')
    W('paths (`.aib`) and the baked vertex colours (`.pvc`, `.cpvs`) are binary.')
    W('')
    W('This is the opposite of the MC:LA PSP port, which was binary on both ends')
    W('and stalled on a vertex encoding that was never reversed. Here the')
    W('vertices are decimal numbers on lines beginning with `v`, so the reading')
    W('side of a port is a parser, not a reverse-engineering problem.')
    W('')

    # --- the cities ---
    W('## Cities')
    W('')
    W('| city | files | size |')
    W('|---|---|---|')
    for c in sorted(os.listdir(city)):
        d = os.path.join(city, c)
        if not os.path.isdir(d):
            continue
        files = [os.path.join(b, f)
                    for b, _dd, ff in os.walk(d) for f in ff]
        W('| `%s` | %d | %.1f MB |' % (c, len(files), size(files) / 1048576.0))
    W('')

    # --- the formats ---
    por_ext = scan(city)
    W('## Formats')
    W('')
    W('| ext | files | kind | what it is |')
    W('|---|---|---|---|')
    for e in sorted(por_ext, key=lambda k: -len(por_ext[k])):
        kind, desc = FORMATS.get(e, ('?', 'not yet identified'))
        measured = is_text(por_ext[e][0])
        if measured is not None:
            real = 'texto' if measured else 'binario'
            if real != kind and e in FORMATS:
                desc += '  **(measured %s, table says %s)**' % (real, kind)
            kind = real
        W('| `%s` | %d | %s | %s |' % (e, len(por_ext[e]), kind, desc))
    W('')

    # --- the hierarchy ---
    W('## How it fits together')
    W('')
    W('```')
    W('losangeles.lvl        numhoods, extents, grid dimensions, hood names')
    W('  l_downtown.hood     unique_component N { name, emin, emax } + instances')
    W('    <name>.xmod       the mesh, as text')
    W('    <name>.cc         LODs present, bounding sphere, inst_cpv')
    W('  losangeles.prop     placed props, each defined by a .pdef')
    W('  losangeles.pvc      baked vertex colours          [binary]')
    W('  losangeles.aib      AI paths                      [binary]')
    W('')
    W('city/<name>/<time>_<weather>/*_cpvs.dat')
    W('                      baked lighting, 9 per city    [binary]')
    W('```')
    W('')

    # --- samples ---
    W('## Samples')
    W('')
    for e in INTERESTING:
        if e not in por_ext:
            continue
        p = sorted(por_ext[e])[0]
        if is_text(p) is False:
            d = open(p, 'rb').read(16)
            W('### `.%s` (binary) — `%s`' % (e, os.path.basename(p)))
            W('')
            W('```')
            W(' '.join('%02X' % b for b in d))
            W('```')
            W('')
            continue
        W('### `.%s` — `%s`' % (e, os.path.basename(p)))
        W('')
        W('```')
        for l in head(p, 8):
            W(l)
        W('```')
        W('')

    txt = '\n'.join(L) + '\n'
    io.open(out_path, 'w', encoding='utf-8', newline='\n').write(txt)
    print('%s: %d formats, %d city files'
          % (out_path, len(por_ext), sum(len(v) for v in por_ext.values())))
    for e in sorted(por_ext, key=lambda k: -len(por_ext[k]))[:8]:
        print('   %-9s %5d' % (e, len(por_ext[e])))


def main():
    out_path = 'mc2_city_inventory.md'
    argv = sys.argv[1:]
    if '-o' in argv:
        i = argv.index('-o')
        out_path = argv[i + 1]
        # Drop BOTH, or the destination gets read back as the input path.
        del argv[i:i + 2]
    args = [a for a in argv if not a.startswith('-')]
    root = args[0] if args else DEFAULT_ROOT
    report(root, out_path)


if __name__ == '__main__':
    main()
